name: Reusable workflow example

on:
  pull_request:
    branches:
      - main

jobs:
  example_job:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
      - uses: .github/workflows/setup.yml@setup
