name: Reusable workflow example

on:
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: setup
    uses: .github/workflows/setup.yaml@setup

  job2:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: ls .