name: Reusable workflow example

on:
  pull_request:
    branches:
      - main

jobs:
  # setup:
  #   name: setup
  #   uses: ./.github/workflows/setup.yaml
  # setup:
  #   name: setup
  #   uses: ./.github/workflows/setup.yaml
  test:
    runs-on: ubuntu-latest
    # needs: setup
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.GITHUB_TOKEN}}
      - uses: ./.github/setup
      - run: ls .
